### ISSUE TITLE
Course image uploads fail on local storage

### ISSUE THREAD

**Issue by grahamb** [instructure/canvas-lms#1064]
### Summary:
When uploading an image to a course in a Canvas instance backed by local storage (not S3), the image appears to fail to upload and the user is presented with an error ("There was an error uploading the image")

### Steps to reproduce:

 1. Enable the "dashboard images for courses" feature in a local-storage backed Canvas instance
 2. Create a course
 3. In the course settings, attempt to upload an image

### Expected behaviour:

The image should upload successfully and the dashboard card should show the image.

### Actual behaviour:

The image _does_ upload successfully; however, the user is presented with a flash message stating that the image upload failed, and the image is not shown on the dashboard card.

### Additional notes:

This appears to only be an issue on local-storage. I have tried this on an Instructure-hosted instance and the upload worked fine. The issue seems to be in [`app/jsx/course_settings/actions.js#L195`](https://github.com/instructure/canvas-lms/blob/stable/app/jsx/course_settings/actions.js#L195). It is attempting to make a `GET` to `successUrl`, which should be the value of `response.data.upload_params.success_url`. On a S3-backed Canvas, the `upload_params` object is set by [`app/models/attachments/s3_storage.rb#L58`](https://github.com/instructure/canvas-lms/blob/stable/app/models/attachments/s3_storage.rb#L58). The corresponding [local storage model](https://github.com/instructure/canvas-lms/blob/stable/app/models/attachments/local_storage.rb#L41) doesn't set the `success_url` parameter, so `successUrl` is `null`.

**Comment by shawniverson** [comment]
Seeing the same issue here after updating to latest stable.

**Comment by shawniverson** [comment]
Old code

```
    uploadFile (event, courseId, ajaxLib = axios) {
      event.preventDefault();
      return (dispatch, getState) => {

        const { type, file } = Helpers.extractInfoFromEvent(event);

        if (Helpers.isValidImageType(type)) {
          dispatch(this.uploadingImage());

          const data = {
            name: file.name,
            size: file.size,
            parent_folder_path: 'course_image',
            type
          };
          ajaxLib.post(`/api/v1/courses/${courseId}/files`, data)
                 .then((response) => {
                    const formData = Helpers.createFormData(response.data.upload_params);
                    formData.append('file', file);
                    ajaxLib.post(response.data.upload_url, formData)
                           .then((response) => {
                               dispatch(this.prepareSetImage(response.data.url, response.data.id, courseId, ajaxLib));
                             })
                           .catch((response) => {
                              dispatch(this.errorUploadingImage());
                           });
                  })
                 .catch((response) => {
                    dispatch(this.errorUploadingImage());
                 });
        } else {
          dispatch(this.rejectedUpload(type));
          $.flashWarning(I18n.t("'%{type}' is not a valid image type (try jpg, png, or gif)", {type}));
        }
      };
    },
```

New Code
```
    uploadFile (event, courseId, ajaxLib = axios) {
      event.preventDefault();
      return (dispatch, getState) => {

        const { type, file } = Helpers.extractInfoFromEvent(event);

        if (Helpers.isValidImageType(type)) {
          dispatch(this.uploadingImage());

          const data = {
            name: file.name,
            size: file.size,
            parent_folder_path: 'course_image',
            type,
            no_redirect: true
          };
          ajaxLib.post(`/api/v1/courses/${courseId}/files`, data)
                 .then((response) => {
                    const formData = Helpers.createFormData(response.data.upload_params);
                    const successUrl = response.data.upload_params.success_url
                    formData.append('file', file);
                    ajaxLib.post(response.data.upload_url, formData)
                           .then((response) => {
                             return ajaxLib.get(successUrl).then((successResp) => {
                               dispatch(this.prepareSetImage(successResp.data.url, successResp.data.id, courseId, ajaxLib));
                             })
                           })
                           .catch((response) => {
                              dispatch(this.errorUploadingImage());
                           });
                  })
                 .catch((response) => {
                    dispatch(this.errorUploadingImage());
                 });
        } else {
          dispatch(this.rejectedUpload(type));
          $.flashWarning(I18n.t("'%{type}' is not a valid image type (try jpg, png, or gif)", {type}));
        }
      };
    },
```

Temporary Workaround, replace new code with old code, then recompile assets on each node.

```
sysadmin@appserver:/var/canvas$ RAILS_ENV=production bundle exec rake canvas:compile_assets
```

**Comment by ally1** [comment]
Hi shawniverson,

I was trying the above method without luck. The issue still there.

**Comment by shawniverson** [comment]
@ally1  Did you restart everything after compiling assets?  I restarted apache and delayed jobs, then it took off for me.

**Comment by ally1** [comment]
Hi @shawniverson ,

I am sorry. We made the second attempt and the issue was resolved.
Thank you!

**Comment by Bicet** [comment]
The issue still unresolved here, after replacing the code and restarting the server.
I'm starting to think that my installation is doomed.

**Comment by bloodyangelred** [comment]
where does this code go?  I'm having the same issue!

**Comment by omarkhan** [comment]
Thanks for this @grahamb. We don't use local storage at Instructure so it will be hard to get a fix prioritized, but if someone opens a pull request I'll try to get it reviewed and merged.

**Comment by shawniverson** [comment]
Appears to be resolved on a recent stable release.
