### ISSUE TITLE
Calendar not displaying 

### ISSUE THREAD

**Issue by dbesancon** [instructure/canvas-lms#1108]
### Summary:
when navigating to the calendar section of an install of the stable version as of 9/7/2017 there is a javascript error preventing the display of the calendar.  The error on the console is:

calendar2.bundle-9fde6804de.js:32 Uncaught TypeError: Cannot read property 'moment' of undefined
    at s (calendar2.bundle-9fde6804de.js:32)
    at Object.r [as now] (calendar2.bundle-9fde6804de.js:32)
    at l.getCurrentDate (calendar2.bundle-9fde6804de.js:15)
    at new l (calendar2.bundle-9fde6804de.js:15)
    at Object.4614 (calendar2.bundle-9fde6804de.js:31)
    at t (vendor.bundle-7726eda3f2.js:1)
    at window.canvasWebpackJsonp (vendor.bundle-7726eda3f2.js:1)
    at calendar2.bundle-9fde6804de.js:1
### Steps to reproduce:

 1. Install stable version
 2. login
 3. navigate to the calendar page

### Additional notes:
Thanks for any assistance.  I do not discount the possibility I missed a step at installation.

**Comment by dbesancon** [comment]
This must have been an installation error.  I reinstalled and it is now fixed.
thanks,

**Comment by captainhurst** [comment]
I can verify that this is still an issue for some installations in multiple environments. I'm looking for a solution now and will post my fix when it's discovered.
