### ISSUE TITLE
External URLs do not load in new tab

### ISSUE THREAD

**Issue by ybakos** [instructure/canvas-lms#1414]
As an instructor,
when creating an External URL as a module item,
and I select "Load in a new tab"
when a student clicks the link,
it does not show the external url in a new tab.

### Summary:
There is a usability nightmare and student engagement issue that could be straightforward to fix. (Please!)
External URLs currently change the window location to the intermediate "This site needs to be opened in a new browser window." page. Clicking on an External URL that is set to "load in a new tab" **should not change the current window location**. Yet it does.

It makes it a huge pain for students who wish to stay on the module page, yet open the External URL in a new tab/window.

### Steps to reproduce:

 1. Create a new External URL module item
 2. Select "Load in a new tab"
 3. Click the created link
 4. Observe the intermediate "This site needs to be opened in a new browser window..." page.

### Expected behavior:
As a student,
when I click on an external URL that the instructor has marked with "Load in a new tab"
a new tab should immediately open with the URL
and my current tab should remain unchanged, still displaying the modules screen.

### Actual behavior:

The window location changes to the "This site needs to be opened in a new browser window."

**Please please remove this ridiculous intermediate page and don't change the window location.**

### Additional notes:

Thank you.

https://community.canvaslms.com/ideas/10144-link-to-external-url

**Comment by eschiebel** [comment]
The fix is not difficult. I am working to understand why it is the way it is so it can be changed without impacting anything else.

**Comment by eschiebel** [comment]
This is fixed and currently in beta.
git commit sha: 6fb74f6fcd692f28d7bf0873862c87c20f4d647a

**Comment by ybakos** [comment]
Thank you, @eschiebel , however this issue is not resolved.
I've tried the beta. 

**Expected behavior:**
As a student,
when I click on an external URL that the instructor has marked with "Load in a new tab"
a new tab should immediately open with the URL
and my current tab should remain unchanged, still displaying the modules screen.

**Comment by ybakos** [comment]
https://community.canvaslms.com/ideas/10144-automatically-open-new-tab-for-linksexternal-tools-set-to-load-in-a-new-tab

**Comment by simonista** [comment]
@ybakos are you trying it in the live production environment? If so it will be fixed there after the deploy on 12/4. The commit referenced above is when the fix was merged into the master branch, if you're using the open source version.

**Comment by ybakos** [comment]
@simonista I tried it on our-org.beta.instructure.com.

**Comment by simonista** [comment]
Ah great, it'll be there 11/21.

**Comment by erinhallmark** [comment]
It's in the beta environment now and will be production on 11/20.

**Comment by ybakos** [comment]
If what is in beta _now_ (11/11/19) is the implementation, then my comments above still hold.

Thank you for the efforts here, but this implementation does not meet the requirements requested by the Canvas community of users.

**Comment by erinhallmark** [comment]
Hi, @ybakos. This issue has been closed, and I see you've also been posting within the feature idea that you've previously included in this thread. Comments about the implementation of this feature have been posted in that idea.

**Comment by eschiebel** [comment]
@ybakos, you said

> Expected behavior:
As a student,
when I click on an external URL that the instructor has marked with "Load in a new tab"
a new tab should immediately open with the URL
and my current tab should remain unchanged, still displaying the modules screen.

I understand what you are requesting, but there is also a significant population of users who prefer to navigate through module items using the previous and next buttons, which are only available on the intermediate page. This solution finds a compromise where the "open in a new window" item does automatically open in a new window, while also preserving the prev/next buttons.
