### ISSUE TITLE
yarn install fails due to @instructure/reactour 

### ISSUE THREAD

**Issue by cribe78** [instructure/canvas-lms#1677]
### Summary:
yarn install fails at the "lib" build step for @instructure/reactour  

OS: Ubuntu 20.04
Node version: 12.18.2 (also confirmed with Node v14)
yarn version: 1.22.4

### Steps to reproduce:

 1.   Clone instructure/canvas-lms, create a new project containing package.json and yarn.lock, or create a new package.json with the minimal dependencies required to reprocuce the issue: 

{
  "name": "reactour-test",
  "version": "1.0.0",
  "description": "testing install of @instructure/reactour",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
        "react": "^16.3.0",
        "react-dom": "^16.3.0",
        "@instructure/reactour": "https://github.com/instructure/reactour#master"
  },
  "author": "CR",
  "license": "ISC"
} 

 2.  run yarn install
 

### Expected behavior:
yarn install completes successfully

### Actual behavior:
yarn install fails:

[4/4] Building fresh packages...
$ npm run lib
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1595442877516-0.0327778506797789/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @instructure/reactour@2.0.1 prelib /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare
> rimraf dist

> @instructure/reactour@2.0.1 lib /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare
> rollup -c

src/index.js → dist/reactour.cjs.js, dist/reactour.esm.js...
[!] (plugin babel) Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/node_modules/@babel/preset-env/lib/index.js
- /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/node_modules/@babel/core/lib/config/files/plugins.js
- /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/node_modules/@babel/core/lib/config/files/index.js
- /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/node_modules/@babel/core/lib/index.js
- /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js
- /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/rollup.config.js
- /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/node_modules/rollup/dist/bin/rollup
src/index.js
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/node_modules/@babel/preset-env/lib/index.js
- /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/node_modules/@babel/core/lib/config/files/plugins.js
- /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/node_modules/@babel/core/lib/config/files/index.js
- /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/node_modules/@babel/core/lib/index.js
- /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js
- /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/rollup.config.js
- /home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/ubuntu/.cache/yarn/v6/.tmp/5cd188ab469e8ca381245e9ee9e9b3c3.f0a05a9de2495db283527fa038c3ff932d059103.prepare/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @instructure/reactour@2.0.1 lib: `rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @instructure/reactour@2.0.1 lib script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-07-22T18_34_39_501Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by cribe78** [comment]
I was able to work around the issue by forking instructure/reactour, deleting .npmrc and yarn.lock from that repository, and then updating package.json to point to my fork

**Comment by alexanderson1993** [comment]
Pardon the delay. I made a change to the @instructure/reactour repository which should resolve this issue. Try installing dependencies again and let me know how it goes.

**Comment by cribe78** [comment]
I was able to install a minimal project depending on only @instructure/reactour and its peer dependencies.   yarn install for a fresh checkout of canvas-lms still failed until I updated yarn.lock and removed the @instructure/reactour reference.

**Comment by pagnchanak** [comment]
> Pardon the delay. I made a change to the @instructure/reactour repository which should resolve this issue. Try installing dependencies again and let me know how it goes.

I just try to install now and still fail during yarn install @instructure/reactour... how to solve this?

**Comment by pagnchanak** [comment]
> I was able to install a minimal project depending on only @instructure/reactour and its peer dependencies. yarn install for a fresh checkout of canvas-lms still failed until I updated yarn.lock and removed the @instructure/reactour reference.

Thanks, this works for me too.

**Comment by pagnchanak** [comment]
> > I was able to install a minimal project depending on only @instructure/reactour and its peer dependencies. yarn install for a fresh checkout of canvas-lms still failed until I updated yarn.lock and removed the @instructure/reactour reference.
> 
> Thanks, this works for me too.

But doing this causing error during compile assets :(

**Comment by cribe78** [comment]
> 
> But doing this causing error during compile assets :(

Yeah, I've run into a couple other issues and have not been able to get through any of the build steps.

**Comment by MissBrandyLea** [comment]
Any progress on this? I also have been unable to complete the build. Hit the same "yarn install fails at the "lib" build step for @instructure/reactour" error wall.

**Comment by OscarPallazhco** [comment]
I also get the same error when I run: `yarn install --pure-lockfile`
I could not continue with the canvas quick start

**Comment by slaughter550** [comment]
This issue was fixed by https://github.com/instructure/canvas-lms/commit/45cb519d526c5b2c04990fc8e277c70e51f1e67e
