### ISSUE TITLE
override terms of use via api not working

### ISSUE THREAD

**Issue by artfulhacker** [instructure/canvas-lms#681]
sending "user[terms_of_use]" true or false does not have any effect on displaying the user agreement for new users created via the api

also the documentation should be clearer, hard to tell if I should be sending true or false to this endpoint.

I can make a PR if you want on the documentation issue.

**Comment by artfulhacker** [comment]
![image](https://cloud.githubusercontent.com/assets/3683852/9592818/d16fb18a-4ffb-11e5-80e7-bfc0c9f02fe8.png)

btw, if you hit submit without checking "I Agree" you get that ^

**Comment by rivernate** [comment]
The terms of use api issue has been fixed here: 0af2e0fbaddd2c1cfd7b1caacecb01c02c1c70ea.  

If you would like to create a new issue for JSON response your getting in the UI that would be great.

**Comment by artfulhacker** [comment]
would this be released on our hosted environment now? still not working for me

**Comment by artfulhacker** [comment]
NM I see it here: https://community.canvaslms.com/docs/DOC-5061
:-)
