### ISSUE TITLE
bundle exec rake db:initial_setup fails from Canvas version-2015-12-12

### ISSUE THREAD

**Issue by kskurtveit** [instructure/canvas-lms#759]
Hi,

After I wanted to deploy a new database to my virtual Canvas environment I noticed the rake initial_setup fails when running Canvas version 2015-12-12. If executing the same task again it works without problems. Could this have something to do with the movement to RAILS4? Or could it just be a separate issue? My workaround for now is to run the same task again. See below for a full trace:

<pre>
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

unknown attribute: max_concurrent/var/www/canvas/config/initializers/active_record.rb:1304:in `ddl_transaction'
/var/www/canvas/config/initializers/active_record.rb:1288:in `block in migrate'
/var/www/canvas/config/initializers/active_record.rb:1264:in `each'
/var/www/canvas/config/initializers/active_record.rb:1264:in `migrate'
/var/www/canvas/lib/tasks/db_load_data.rake:239:in `block (2 levels) in <top (required)>'
ActiveRecord::UnknownAttributeError: unknown attribute: max_concurrent
/var/www/canvas/config/initializers/active_record.rb:1304:in `ddl_transaction'
/var/www/canvas/config/initializers/active_record.rb:1288:in `block in migrate'
/var/www/canvas/config/initializers/active_record.rb:1264:in `each'
/var/www/canvas/config/initializers/active_record.rb:1264:in `migrate'
/var/www/canvas/lib/tasks/db_load_data.rake:239:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
</pre>

**Comment by ccutrer** [comment]
This is already fixed in the latest stable release of Canvas. The problem was an ordering problem adding a new column to a table, but during initial setup the column is expected to be there when it won't be added until later.

**Comment by emilal** [comment]
This problem still appears when pulling `--branch stable`. Otherwise it looks like the same issue as #773. Running `db:initial_setup` twice makes the problem disappear.

This is in [a docker container](https://github.com/matematikk-mooc/mmooc-docker-canvas/blob/9b78dea44cdb6c169a1631d576205324620d0890/Dockerfile) based on Ubuntu 15.10 (the database runs in another container). (This and #773 are the results I get from google, so hopefully this'll decrease the likelihood of [xkcd/979](https://xkcd.com/979/).)

**Comment by kskurtveit** [comment]
Just thought I should update this issue. Initdb is working again on the 2016-04-02.13 release.
